### ISSUE TITLE
API Error: System with id "xxx" not found

### ISSUE THREAD

**Issue by target2804** [henrygd/beszel-docs#9]
Hello,

I do have the problem that occasionally the service doesnt seem to integrate into my gethomepage widget anymore. I run the beszel hub & agent using this compose.yml:
```
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - ./beszel_data:/beszel_data
      - ./beszel_socket:/beszel_socket

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      # Do not remove quotes around the key
      KEY: 'xxxxxxxxxxxxxxxxxxxxxx'
```

In my gethomepage services file, I integrate the stats to my dashboard like so:
   
```
  - Homeserver Health:
        href: https://beszel.abr-home.de
        description: Beszel
        icon: beszel.svg
        widget:
          type: beszel
          url: http://192.168.178.9:8090
          username: me@x.com
          password: ttttt
          systemId: owh1bu6ik07pxn3
          version: 2
          fields: ["status", "cpu", "memory", "network"]

    - Pihole Health:
        href: https://beszel.abr-home.de
        description: Beszel
        icon: beszel.svg
        widget:
          type: beszel
          url: http://192.168.178.9:8090
          username: me@x.com
          password: ttttt
          systemId: l971u0wgv5jmw79
          version: 2
          fields: ["status", "cpu", "memory", "network"]
```

The Homeserver (192.168.178.9) is where i run hub & agent. On my Pihole I only run the agent and display the data via the hub on my homeserver.
The Pihole Service widget is working fine, it never stopped working. In the agent on my pihole I of course configure:
```
services:
  beszel-agent:
    image: "henrygd/beszel-agent"
    container_name: "beszel-agent"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: 45876
      KEY: "xxxxxxxxxxxxx"

```
 The Homeserver Health Widget however works only 50% of the time. The systemID is correct as it otherwise would never work. The Pihole widget always works.
The agents both put all the necessary info in my hub and there is no data inconsistency:

![Image](https://github.com/user-attachments/assets/480fcd72-10ca-424e-bbd4-2b9612c1f96a)

The beszel logs show:

> 2025/03/19 13:07:13 Server started at http://0.0.0.0:8090
> 
> ├─ REST API:  http://0.0.0.0:8090/api/
> 
> └─ Dashboard: http://0.0.0.0:8090/_/

The agent logs:

> 2025/03/18 10:23:07 INFO Detected root device name=mmcblk0p2
> 2025/03/18 10:23:07 INFO Detected network interface name=eth0 sent=7664 recv=3865
> 2025/03/18 10:23:09 INFO Starting SSH server addr=/beszel_socket/beszel.sock network=unix
> --> worked after that start. didn´t work anymore today morning.
> 2025/03/19 13:08:17 INFO Detected root device name=mmcblk0p2
> 2025/03/19 13:08:17 INFO Detected network interface name=eth0 sent=620491482 recv=13282004740
> 2025/03/19 13:08:17 INFO Starting SSH server addr=/beszel_socket/beszel.sock network=unix
> --> didn´t work either after restarting both agent and hub.

This is the result i get atm on my dashboard:

![Image](https://github.com/user-attachments/assets/423c8e6f-5dc7-49a7-b634-d301ff62976a)
